jeecloud.exception.service.alreadyExists=Dienst mit dem Namen "{0}" und URL "{1}" ist bereits vorhanden
jeecloud.exception.service.notExists=Dienst mit dem Namen "{0}" existiert nicht